<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="structures" nsURI="urn://Ocpp/Cp/2015/10" nsPrefix="structures">
  <eClassifiers xsi:type="ecore:EClass" name="MeasurementNotification" eSuperTypes="#//Notification">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" eType="#//Unit" defaultValueLiteral="W"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="State">
    <eLiterals name="ON"/>
    <eLiterals name="OFF" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Unit">
    <eLiterals name="m"/>
    <eLiterals name="V" value="2"/>
    <eLiterals name="A" value="3"/>
    <eLiterals name="W" value="4"/>
    <eLiterals name="Wh" value="6"/>
    <eLiterals name="VA" value="8"/>
    <eLiterals name="var" value="9"/>
    <eLiterals name="Celsius" value="10"/>
    <eLiterals name="K" value="11"/>
    <eLiterals name="Percent" value="12"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StateNotification" eSuperTypes="#//Notification">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="#//State"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Notification" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timestamp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source_id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
