version: '2'

services:

    mongodb:
        image: mongo:latest
        volumes:
            - ./data/mongo_dev/:/data/mongo_dev/
        entrypoint: [ "/usr/bin/mongod", "--dbpath", "/data", "--journal", "--bind_ip", "0.0.0.0"]
        ports:
            - "27017:27017"
            - "28017:28017"
        networks:
            - mongo
            
    sensinact:
        image: jena/sensinact:latest
        ports:
            - "8080:8080"
        networks:
            - mongo
networks:    
    mongo:

